# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bac41502f7109244ee765995f5df8038541353ccea04df317af292365f2cc4f102b0e15fd31f7a586a070cf04add13fe292ae264f1aebd73e0e044f584cac5d

test:
  secret_key_base: cbd253663cd561cd5d8b38ec6e8a2e670421e6f138ccb97108896ebb40eacc1a8269fd8fda8a4404c808a8706067bb87563a2c43cf631cbb91c742494f5ff218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
